<a href="https://colab.research.google.com/github/2303A51337Srivarsha/b_10_python-for-data-science/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)

[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [2]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)

[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


In [3]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[ 98  13  19  72]
 [ 85  79  80  34]
 [ 45  16   3   9]
 [100  26  47  14]]

Row-wise Mean (per student):
 [50.5  69.5  18.25 46.75]

Column-wise Mean (per subject):
 [82.   33.5  37.25 32.25]

Standard Deviation of all scores: 33.13513995745303
Variance of all scores: 1097.9375

Maximum Score: 100
Minimum Score: 3


In [4]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)

Original Image:
 [[[155  71  94]
  [ 53 127 229]
  [145  93 108]]

 [[184 128 212]
  [171 195 241]
  [168 231  73]]

 [[ 39 135 116]
  [229 141  14]
  [ 50 234 254]]]

Red Channel:
 [[155  53 145]
 [184 171 168]
 [ 39 229  50]]

Green Channel:
 [[ 71 127  93]
 [128 195 231]
 [135 141 234]]

Blue Channel:
 [[ 94 229 108]
 [212 241  73]
 [116  14 254]]

Average Red: 132.66666666666666
Average Green: 150.55555555555554
Average Blue: 149.0

Brightened Image:
 [[[205 121 144]
  [103 177 255]
  [195 143 158]]

 [[234 178 255]
  [221 245 255]
  [218 255 123]]

 [[ 89 185 166]
  [255 191  64]
  [100 255 255]]]

Darkened Image:
 [[[105  21  44]
  [  3  77 179]
  [ 95  43  58]]

 [[134  78 162]
  [121 145 191]
  [118 181  23]]

 [[  0  85  66]
  [179  91   0]
  [  0 184 204]]]
