<a href="https://colab.research.google.com/github/2303A51337Srivarsha/b_10_python-for-data-science/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)

[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [6]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)

[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


In [7]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[83 87 54 90]
 [21 39 62  6]
 [27 59 12 64]
 [72 33 99 59]]

Row-wise Mean (per student):
 [78.5  32.   40.5  65.75]

Column-wise Mean (per subject):
 [50.75 54.5  56.75 54.75]

Standard Deviation of all scores: 27.771880450376422
Variance of all scores: 771.27734375

Maximum Score: 99
Minimum Score: 6


In [8]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)

Original Image:
 [[[250 234 180]
  [ 76 152  47]
  [ 56 127 201]]

 [[ 41 140 140]
  [ 43 174 228]
  [255 202  46]]

 [[ 30 212 182]
  [206  19  43]
  [125   9  58]]]

Red Channel:
 [[250  76  56]
 [ 41  43 255]
 [ 30 206 125]]

Green Channel:
 [[234 152 127]
 [140 174 202]
 [212  19   9]]

Blue Channel:
 [[180  47 201]
 [140 228  46]
 [182  43  58]]

Average Red: 120.22222222222223
Average Green: 141.0
Average Blue: 125.0

Brightened Image:
 [[[255 255 230]
  [126 202  97]
  [106 177 251]]

 [[ 91 190 190]
  [ 93 224 255]
  [255 252  96]]

 [[ 80 255 232]
  [255  69  93]
  [175  59 108]]]

Darkened Image:
 [[[200 184 130]
  [ 26 102   0]
  [  6  77 151]]

 [[  0  90  90]
  [  0 124 178]
  [205 152   0]]

 [[  0 162 132]
  [156   0   0]
  [ 75   0   8]]]
